[important]
resolution = 0.6           # voxel size (meters), v in the paper, default 0.1
inflate_unknown = 1         # d_p in the paper, default 1
inflate_hits_dist = 0.4    # d_s in the paper, default 0.2
forward_hit_extend_distance = 1.8

kMinHitFrames = 7
kMinLifeSpanFrames = 7

# ===> Ground Segmentation, so that we will not count ground
[ground]
enable = true
distance = 0.15
angle = 0.15
planeDistance = 0.1
ground_min_z=-2.0
ground_max_z=-1.2

# ===> Filter
[filter]
enable = false
filterMeanK = 100
StddevMulThresh = 2.0

[fdage]
replaceInputPly=true
output_map=true
select_m = 50
select_n = -100

# ----------- No need to modify if you are not professional dufoer or ufoer.
# ----------- Deeper Parameter for debugging potential better result --------

[integration]
inflate_unknown_compensation = true
ray_passthrough_hits = true
down_sampling_method = "center"       # ["none", "center", "centroid", "uniform"]
max_range = -1                        # Maximum range to integrate
only_valid = false                    # Only do ray casting for points within 'max_range'
hit_depth = 0                         # Level of the octree to integrate hits
miss_depth = 0                        # Level of the octree to integrate misses
parallel = true                       # Use parallel execution for integration
num_threads = 0                       # Number of threads to use, 8 times number of physical cores seems to be a good number and it is chosen if 0 is given

[map]
levels = 20      # Levels of the octree

[dataset]
first = 0 # First pcd index
last = -1 # Last pcd index (-1 equals all)
num = -1  # Number of pcd files to read (-1 equals all)

[printing]
verbose = false
debug = false

[output]
filename = "dufomap_output"
voxel_map = false # whether to save the voxel map or raw point level
raycasting = false
